#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
 
modelVersion: 2.0  
 
documents:
  - name: VA-report
    files:
      - ../build/va-reports/Vulnerability_Report_2.0.md # this file finds path to Vulnerability_Report_2.0.md file 