Kubeaudit:
  Product: 'Schema Registry'
  ClusterMode:
    Scan: True
    KubeconfigFile: "kubeconfig"        #default is config  #Mount the dir containing this file to conf
    Namespace: "eric-oss-schema-registry-sr-install-va"   #Optional, If Namespace given, auditing will be done only for the mentioned namespaces. (Comma separated if multiple ns)
    AuditPickerFile: ""                 #Optional, #https://github.com/Shopify/kubeaudit#configuration-file, #Mount the dir containing this file to conf
    Autofix : False                     #(or True it if needed)
    AutofixedFile:                      #Mandatory If Autofix enabled, file name inside Mounted reports dir to add corrected config
    ReportFormat: 'json'                #available options: logrus,pretty,json. pretty is the default if not given.
    DisplayReportConsole: True          #Make it true if you want the reports to be displayed in console
  ManifestMode:
    Scan: True
    armLinks:
      Links:
      valuesOverride:                   #Array #If override is needed, add the values yaml names in the same order as arm links, if none, mark it ''
    armLinksWithAuth:                   #Add ARM links which requires auth here.
      Links:
      armUser:                          #mandatory if Links #signum
      armEncryptedPwd:                  #Mandatory if Links #The encrypted password from ARM link
      valuesOverride:                   #Array ##If override is needed, add the values yaml names in the same order as arm links, if none, mark it ''
    offlineArtifacts:
      name:
      valuesOverride:                   ##If override is needed, add the values yaml names in the same order as offlineArtifacts name, if none, mark it ''                       #mount this to /opt/va-scan-kubeaudit/conf dir
    AuditPickerFile: ""                 #Optional #https://github.com/Shopify/kubeaudit#configuration-file, #Mount the dir containing this file to conf
    Autofix : False                     #(or True it if needed)
    AutofixDir: "fixed"                 #Mandatory If Autofix enabled, folder name inside mounted reports dir to add corrected Yamls
    ReportFormat: 'json'                #logrus,pretty are other available options. Pretty is the default if not given.
    DisplayReportConsole: True          #Make it true if you want the reports to be displayed in console
  CustomRun:
    Scan: False                         #if True, overrides all the above options.
    #Give any valid kubeaudit command here
    #Place and mount the needed config files in /opt/va-scan-kubeaudit/conf/"
    Parameters:
    DisplayReportConsole: False         #Make it true if you want the reports to be displayed in console