{{- if .Values.brAgent.enabled }}
{{- $global := fromJson (include "eric-oss-schema-registry-sr.global" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "eric-oss-schema-registry-sr.agentName" . }}
  labels:
    {{- include "eric-oss-schema-registry-sr.agent.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-oss-schema-registry-sr.annotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "eric-oss-schema-registry-sr.agentName" . }}
      release: {{ .Release.Name | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "eric-oss-schema-registry-sr.agent.labels" . | nindent 8 }}
      annotations:
        {{- include "eric-oss-schema-registry-sr.annotations" . | nindent 8 }}
        {{- if .Values.brAgent.backupTypeList }}
        {{- if (index .Values.brAgent.backupTypeList 0) }}
        backupType: {{- template "eric-oss-schema-registry-sr.agent.backupTypes"  . }}
        {{- end }}
        {{- end }}
    spec:
      {{- if include "eric-oss-schema-registry-sr.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-oss-schema-registry-sr.pullSecrets" . }}
      {{- end }}
      {{- if (index .Values "podPriority" "priorityClassName") }}
      priorityClassName: {{ (index .Values "podPriority" "priorityClassName") | quote }}
      {{- end }}
      {{- include "eric-oss-schema-registry-sr.brAgentNodeSelector" . | nindent 6 }}
      containers:
      - name:  {{ .Chart.Name }}-agent
        imagePullPolicy: {{ or .Values.imageCredentials.bragent.registry.imagePullPolicy (include "eric-oss-schema-registry-sr.imagePullPolicy" .) }}
        image: {{ template "eric-oss-schema-registry-sr.imagePath" (merge (dict "imageName" "bragent") .) }}
        resources:
{{ toYaml .Values.resources.brAgent | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
              - all
        env:
          - name: TZ
            value: {{ $global.timezone | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.brAgent.logLevel | quote }}
          - name: SERVICE_ID
            value: {{ template "eric-oss-schema-registry-sr.broServiceName" . }}
          - name: AGENT_DATA_CHANNEL_TIMEOUT_SECS
            value: {{ .Values.brAgent.grpc.backup.dataChannelTimeoutSecs | quote }}
          - name: AGENT_FRAGMENT_CHUNK_SIZE
            value: {{ .Values.brAgent.grpc.backup.fragmentChunkSize | quote }}
        readinessProbe:
          exec:
            command:
              - "pgrep"
              - "-fl"
              - "java"
          initialDelaySeconds: {{ .Values.probes.general.readinessProbe.initialDelaySeconds }}
          failureThreshold: {{ .Values.probes.general.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.probes.general.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.probes.general.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.probes.general.readinessProbe.timeoutSeconds }}
        livenessProbe:
          exec:
            command:
              - "pgrep"
              - "-fl"
              - "java"
          initialDelaySeconds: {{ .Values.probes.general.livenessProbe.initialDelaySeconds }}
          failureThreshold: {{ .Values.probes.general.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.probes.general.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.probes.general.livenessProbe.timeoutSeconds }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
