#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-schema-registry-sr.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-schema-registry-sr.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ template "eric-oss-schema-registry-sr.name" . }}-int-cert
spec:
  kubernetes:
    generatedSecretName: {{ template "eric-oss-schema-registry-sr.name" . }}-secret
    certificateName: "cert.pem"
    privateKeyName: "key.pem"
  certificate:
    subject:
      cn: {{ template "eric-oss-schema-registry-sr.name" . }}
    issuer:
      reference:  {{ .Values.messaging.kafka.issuerReference | quote }}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: false
{{- end }}